// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbhlP_6igD4w_28K-FWdxObmhlASUP5vk',
    appId: '1:995242381642:web:501ef33fb90b82cfdcf1b3',
    messagingSenderId: '995242381642',
    projectId: 'gold-digger-51a79',
    authDomain: 'gold-digger-51a79.firebaseapp.com',
    storageBucket: 'gold-digger-51a79.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArB6wVLWBD3bcQ29sV7nC0hXCgy0OnldM',
    appId: '1:995242381642:android:b5fb8a2ed33f82f9dcf1b3',
    messagingSenderId: '995242381642',
    projectId: 'gold-digger-51a79',
    storageBucket: 'gold-digger-51a79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEzh0vdQSG63pSySkIE_Ry3jHuZLAUC1s',
    appId: '1:995242381642:ios:c71002b973c79942dcf1b3',
    messagingSenderId: '995242381642',
    projectId: 'gold-digger-51a79',
    storageBucket: 'gold-digger-51a79.appspot.com',
    iosBundleId: 'com.example.se109Goldstore',
  );
}
